<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4f3tjtl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4f3tjtl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4f3tjtl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4f3tjtl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4f3tjtl\appDevDebugProjectContainer(array(
    'container.build_hash' => '4f3tjtl',
    'container.build_id' => 'c3392d9b',
    'container.build_time' => 1519893889,
));
